apiVersion: v1
kind: Service
metadata:
  name: taxlens-postgrest
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: taxlens-db
    app.kubernetes.io/component: postgrest
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgrest.port }}
      targetPort: {{ .Values.postgrest.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: taxlens-db
    app.kubernetes.io/component: postgrest
