apiVersion: v1
kind: Service
metadata:
  name: taxlens-pg
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: taxlens-db
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: taxlens-db
    app.kubernetes.io/component: postgres
