"""PDF tax form generator using ReportLab — Forms 1040, Schedules A/B/D, IL-1040."""

from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors

from tax_engine import TaxResult

WIDTH, HEIGHT = letter  # 612 x 792


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------
def fmt(amount: float) -> str:
    """Format dollar amount."""
    if amount == 0:
        return "—"
    if amount < 0:
        return f"({abs(amount):,.2f})"
    return f"{amount:,.2f}"


def draw_header(c: canvas.Canvas, form_name: str, form_title: str, tax_year: int, y: float) -> float:
    """Draw form header. Returns new y position."""
    # Top border
    c.setStrokeColor(colors.HexColor("#1a237e"))
    c.setLineWidth(2)
    c.line(50, y, WIDTH - 50, y)
    y -= 5

    # Form number (left)
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.HexColor("#1a237e"))
    c.drawString(55, y - 20, form_name)

    # Title (center)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(WIDTH / 2, y - 18, form_title)

    # Tax year (right)
    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(WIDTH - 55, y - 20, str(tax_year))

    c.setFont("Helvetica", 7)
    c.setFillColor(colors.gray)
    c.drawCentredString(WIDTH / 2, y - 30, "Department of the Treasury — Internal Revenue Service")
    c.drawCentredString(WIDTH / 2, y - 39, "DRAFT — Generated by TaxLens for review purposes only")

    y -= 45
    c.setStrokeColor(colors.HexColor("#1a237e"))
    c.setLineWidth(1)
    c.line(50, y, WIDTH - 50, y)
    c.setFillColor(colors.black)

    return y - 10


def draw_section(c: canvas.Canvas, title: str, y: float) -> float:
    """Draw a section header."""
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(colors.HexColor("#1a237e"))
    c.drawString(55, y, title)
    c.setLineWidth(0.5)
    c.setStrokeColor(colors.HexColor("#bbdefb"))
    c.line(55, y - 3, WIDTH - 55, y - 3)
    c.setFillColor(colors.black)
    return y - 16


def draw_line(c: canvas.Canvas, line_num: str, description: str, amount: float, y: float,
              bold: bool = False, indent: int = 0) -> float:
    """Draw a single form line with number, description, and amount."""
    font = "Helvetica-Bold" if bold else "Helvetica"
    c.setFont(font, 8)

    x_num = 58 + indent
    x_desc = 80 + indent
    x_amt = WIDTH - 60

    if line_num:
        c.setFillColor(colors.HexColor("#1a237e"))
        c.drawString(x_num, y, line_num)
    c.setFillColor(colors.black)
    c.drawString(x_desc, y, description)

    # Amount box
    if bold:
        c.setStrokeColor(colors.HexColor("#1a237e"))
        c.setFillColor(colors.HexColor("#e8eaf6"))
        c.rect(x_amt - 80, y - 3, 130, 13, fill=1, stroke=1)
        c.setFillColor(colors.HexColor("#1a237e"))
    else:
        c.setStrokeColor(colors.HexColor("#e0e0e0"))
        c.rect(x_amt - 80, y - 3, 130, 13, fill=0, stroke=1)
        c.setFillColor(colors.black)

    c.setFont(font, 8)
    c.drawRightString(x_amt + 45, y, fmt(amount))
    c.setFillColor(colors.black)

    return y - 16


def draw_info_row(c: canvas.Canvas, label: str, value: str, y: float, x: float = 58) -> float:
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.gray)
    c.drawString(x, y, label)
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 9)
    c.drawString(x + 80, y, value)
    return y - 14


def draw_filer_info(c: canvas.Canvas, result: TaxResult, y: float) -> float:
    """Draw filer information block."""
    y = draw_section(c, "Filing Information", y)
    filer = result.filer

    status_labels = {"single": "Single", "mfj": "Married Filing Jointly",
                     "hoh": "Head of Household", "mfs": "Married Filing Separately"}

    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)

    if result.filing_status == "mfj" and result.spouse:
        y = draw_info_row(c, "Spouse:", f"{result.spouse.first_name} {result.spouse.last_name}", y)
        y = draw_info_row(c, "Spouse SSN:", result.spouse.ssn, y)

    y = draw_info_row(c, "Address:", filer.address_street, y)
    y = draw_info_row(c, "City/St/Zip:",
                      f"{filer.address_city}, {filer.address_state} {filer.address_zip}", y)
    y = draw_info_row(c, "Filing Status:", status_labels.get(result.filing_status, result.filing_status), y)

    if result.num_dependents > 0:
        y = draw_info_row(c, "Dependents:", str(result.num_dependents), y)

    return y - 5


# ---------------------------------------------------------------------------
# Form 1040
# ---------------------------------------------------------------------------
def generate_1040(result: TaxResult) -> BytesIO:
    """Generate Form 1040 PDF."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "1040", "U.S. Individual Income Tax Return", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    # --- Income ---
    y = draw_section(c, "Income", y)
    y = draw_line(c, "1a", "Wages, salaries, tips (from W-2s)", result.line_1a_wages, y)

    # W-2 detail
    for i, w in enumerate(result.w2s):
        c.setFont("Helvetica", 7)
        c.setFillColor(colors.gray)
        c.drawString(100, y + 4, f"W-2 #{i+1}: {w.employer_name} (EIN: {w.employer_ein}) — ${w.wages:,.2f}")
        c.setFillColor(colors.black)
        y -= 12

    y = draw_line(c, "2b", "Taxable interest", result.line_2b_taxable_interest, y)
    y = draw_line(c, "3a", "Qualified dividends", result.line_3a_qualified_dividends, y)
    y = draw_line(c, "3b", "Ordinary dividends", result.line_3b_ordinary_dividends, y)
    y = draw_line(c, "7", "Capital gain or (loss) — from Schedule D", result.line_7_capital_gain_loss, y)
    if result.line_8a_business_income != 0:
        y = draw_line(c, "8a", "Business income or (loss) — from Schedule C", result.line_8a_business_income, y)
    y = draw_line(c, "8", "Other income", result.line_8_other_income, y)
    y = draw_line(c, "9", "Total income", result.line_9_total_income, y, bold=True)

    # --- Adjustments ---
    y = draw_section(c, "Adjustments to Income", y)
    if result.se_tax_deduction > 0:
        y = draw_line(c, "", "Deductible part of self-employment tax", result.se_tax_deduction, y)
    y = draw_line(c, "10", "Total adjustments", result.line_10_adjustments, y)
    y = draw_line(c, "11", "Adjusted gross income (AGI)", result.line_11_agi, y, bold=True)

    # --- Deductions ---
    y = draw_section(c, "Deductions", y)
    dtype = f"{'Standard' if result.deduction_type == 'standard' else 'Itemized'} deduction"
    y = draw_line(c, "12", f"{dtype} ({result.deduction_type})", result.line_13_deduction, y)
    if result.qbi_deduction > 0:
        y = draw_line(c, "13", "Qualified business income deduction (Section 199A)", result.qbi_deduction, y)
    y = draw_line(c, "15", "Taxable income", result.line_15_taxable_income, y, bold=True)

    # --- Tax ---
    y = draw_section(c, "Tax and Credits", y)
    y = draw_line(c, "16", "Tax (from tax table / brackets)", result.line_16_tax, y)
    if result.capital_gains_tax > 0:
        y = draw_line(c, "", "Capital gains tax (preferential rates)", result.capital_gains_tax, y)
    if result.se_tax > 0:
        y = draw_line(c, "", "Self-employment tax (Schedule SE)", result.se_tax, y)
    if result.line_27_ctc > 0:
        y = draw_line(c, "27", "Child tax credit", -result.line_27_ctc, y)
    y = draw_line(c, "24", "Total tax", result.line_24_total_tax, y, bold=True)

    # --- Payments ---
    y = draw_section(c, "Payments", y)
    y = draw_line(c, "25a", "Federal income tax withheld (W-2s)", result.line_25_federal_withheld, y)
    if result.estimated_payments > 0:
        y = draw_line(c, "26", "Estimated tax payments", result.estimated_payments, y)
    y = draw_line(c, "33", "Total payments", result.line_33_total_payments, y, bold=True)

    # --- Refund / Owed ---
    y -= 5
    if result.line_34_overpaid > 0:
        y = draw_section(c, "Refund", y)
        y = draw_line(c, "34", "AMOUNT OVERPAID (REFUND)", result.line_34_overpaid, y, bold=True)
    else:
        y = draw_section(c, "Amount You Owe", y)
        y = draw_line(c, "37", "AMOUNT YOU OWE", result.line_37_owed, y, bold=True)

    # Effective rate
    y -= 10
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.gray)
    if result.line_11_agi > 0:
        eff_rate = (result.line_24_total_tax / result.line_11_agi) * 100
        c.drawString(58, y, f"Effective federal tax rate: {eff_rate:.1f}%")
    c.setFillColor(colors.black)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Schedule A — Itemized Deductions
# ---------------------------------------------------------------------------
def generate_schedule_a(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "Schedule A", "Itemized Deductions", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    y = draw_section(c, "Medical and Dental Expenses", y)
    y = draw_line(c, "1", "Medical and dental expenses", result.sched_a_medical + result.line_11_agi * 0.075 if result.sched_a_medical > 0 else 0, y)
    y = draw_line(c, "3", f"7.5% of AGI ({fmt(result.line_11_agi)} × 7.5%)", result.line_11_agi * 0.075, y)
    y = draw_line(c, "4", "Deductible medical expenses", result.sched_a_medical, y, bold=True)

    y = draw_section(c, "Taxes You Paid", y)
    y = draw_line(c, "5a", "State and local income taxes", 0, y)  # computed in SALT
    y = draw_line(c, "5b", "State and local real estate taxes", 0, y)
    y = draw_line(c, "5d", "Total state/local taxes (SALT — capped at $10,000)", result.sched_a_salt, y, bold=True)

    y = draw_section(c, "Interest You Paid", y)
    y = draw_line(c, "8a", "Home mortgage interest", result.sched_a_mortgage_interest, y, bold=True)

    y = draw_section(c, "Gifts to Charity", y)
    y = draw_line(c, "12", "Gifts by cash or check", result.sched_a_charitable, y, bold=True)

    y -= 10
    y = draw_section(c, "Total Itemized Deductions", y)
    y = draw_line(c, "17", "TOTAL ITEMIZED DEDUCTIONS", result.sched_a_total, y, bold=True)

    c.setFont("Helvetica", 8)
    c.setFillColor(colors.gray)
    y -= 10
    std = result.standard_deduction
    if result.sched_a_total > std:
        c.drawString(58, y, f"Itemized ({fmt(result.sched_a_total)}) exceeds standard deduction ({fmt(std)}) — itemizing saves ${result.sched_a_total - std:,.2f}")
    else:
        c.drawString(58, y, f"Standard deduction ({fmt(std)}) exceeds itemized ({fmt(result.sched_a_total)}) — standard deduction is better")
    c.setFillColor(colors.black)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Schedule B — Interest and Dividends
# ---------------------------------------------------------------------------
def generate_schedule_b(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "Schedule B", "Interest and Ordinary Dividends", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    y = draw_section(c, "Part I — Interest", y)
    y = draw_line(c, "1", "Taxable interest income", result.sched_b_interest_total, y)
    y = draw_line(c, "4", "Total interest (to Form 1040, Line 2b)", result.sched_b_interest_total, y, bold=True)

    y = draw_section(c, "Part II — Ordinary Dividends", y)
    y = draw_line(c, "5", "Ordinary dividends", result.sched_b_dividends_total, y)
    y = draw_line(c, "6", "Total dividends (to Form 1040, Line 3b)", result.sched_b_dividends_total, y, bold=True)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Schedule D — Capital Gains and Losses
# ---------------------------------------------------------------------------
def generate_schedule_d(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "Schedule D", "Capital Gains and Losses", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    # Part I — Short-term
    y = draw_section(c, "Part I — Short-Term Capital Gains and Losses (held one year or less)", y)

    short_txns = [t for t in result.capital_transactions if not t.is_long_term]
    for t in short_txns:
        c.setFont("Helvetica", 7)
        c.drawString(65, y, f"{t.description}")
        c.drawString(220, y, f"Acquired: {t.date_acquired}")
        c.drawString(320, y, f"Sold: {t.date_sold}")
        c.drawString(410, y, f"Proceeds: ${t.proceeds:,.2f}")
        c.drawString(500, y, f"Gain/Loss: ${t.gain_loss:,.2f}")
        y -= 12

    y = draw_line(c, "7", "Net short-term capital gain or (loss)", result.sched_d_short_term_gain, y, bold=True)

    # Part II — Long-term
    y = draw_section(c, "Part II — Long-Term Capital Gains and Losses (held more than one year)", y)

    long_txns = [t for t in result.capital_transactions if t.is_long_term]
    for t in long_txns:
        c.setFont("Helvetica", 7)
        c.drawString(65, y, f"{t.description}")
        c.drawString(220, y, f"Acquired: {t.date_acquired}")
        c.drawString(320, y, f"Sold: {t.date_sold}")
        c.drawString(410, y, f"Proceeds: ${t.proceeds:,.2f}")
        c.drawString(500, y, f"Gain/Loss: ${t.gain_loss:,.2f}")
        y -= 12

    y = draw_line(c, "15", "Net long-term capital gain or (loss)", result.sched_d_long_term_gain, y, bold=True)

    # Part III — Summary
    y = draw_section(c, "Part III — Summary", y)
    y = draw_line(c, "16", "Net capital gain or (loss) — to Form 1040, Line 7", result.sched_d_net_gain, y, bold=True)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Schedule C — Profit or Loss from Business
# ---------------------------------------------------------------------------
def generate_schedule_c(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "Schedule C", "Profit or Loss From Business", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    for idx, biz in enumerate(result.sched_c_businesses):
        if idx > 0:
            y -= 10
        y = draw_section(c, f"Business #{idx+1}: {biz.get('name', 'Business')}", y)
        if biz.get("type"):
            c.setFont("Helvetica", 7)
            c.setFillColor(colors.gray)
            c.drawString(65, y + 4, f"Type: {biz['type']}")
            c.setFillColor(colors.black)
            y -= 12

        y = draw_line(c, "1", "Gross receipts or sales", biz.get("gross_receipts", 0), y)
        y = draw_line(c, "4", "Cost of goods sold", biz.get("cogs", 0), y)
        y = draw_line(c, "7", "Gross profit", biz.get("gross_profit", 0), y, bold=True)
        y = draw_line(c, "28", "Total expenses", biz.get("expenses", 0), y)
        y = draw_line(c, "31", "Net profit or (loss)", biz.get("net_profit", 0), y, bold=True)

        # Page break if running low
        if y < 150 and idx < len(result.sched_c_businesses) - 1:
            c.showPage()
            y = HEIGHT - 40

    y -= 10
    y = draw_section(c, "Total — All Businesses", y)
    y = draw_line(c, "", "TOTAL NET BUSINESS INCOME — to Form 1040, Line 8a",
                  result.sched_c_total_profit, y, bold=True)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Schedule SE — Self-Employment Tax
# ---------------------------------------------------------------------------
def generate_schedule_se(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "Schedule SE", "Self-Employment Tax", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    y = draw_section(c, "Part I — Self-Employment Tax", y)
    y = draw_line(c, "2", "Net earnings from self-employment (from Schedule C)", result.sched_se_net_earnings, y)
    y = draw_line(c, "3", f"92.35% of net earnings", result.sched_se_taxable, y)
    y = draw_line(c, "4a", "Social Security tax portion (12.4%)", result.sched_se_ss_tax, y)
    y = draw_line(c, "4b", "Medicare tax portion (2.9%)", result.sched_se_medicare_tax, y)
    y = draw_line(c, "5", "TOTAL SELF-EMPLOYMENT TAX", result.sched_se_total, y, bold=True)

    y -= 10
    y = draw_section(c, "Deduction", y)
    y = draw_line(c, "6", "Deductible part of SE tax (50%) — to Form 1040 adjustments",
                  result.se_tax_deduction, y, bold=True)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# IL-1040 — Illinois Individual Income Tax Return
# ---------------------------------------------------------------------------
def generate_il1040(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "IL-1040", "Illinois Individual Income Tax Return", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    y = draw_section(c, "Income", y)
    y = draw_line(c, "1", "Federal adjusted gross income (from 1040 Line 11)", result.il_line_1_federal_agi, y)
    y = draw_line(c, "3", "Additions to income", result.il_line_3_additions, y)
    y = draw_line(c, "7", "Illinois base income", result.il_line_7_base_income, y, bold=True)

    y = draw_section(c, "Exemptions", y)
    num_ex = 1
    if result.filing_status == "mfj" and result.spouse:
        num_ex = 2
    num_ex += result.num_dependents
    y = draw_line(c, "9", f"Exemptions ({num_ex} × $2,775)", result.il_line_9_exemptions, y)
    y = draw_line(c, "10", "Illinois taxable income", result.il_line_10_taxable, y, bold=True)

    y = draw_section(c, "Tax", y)
    y = draw_line(c, "11", f"Income tax (4.95% × {fmt(result.il_line_10_taxable)})", result.il_line_11_tax, y, bold=True)

    y = draw_section(c, "Payments and Credits", y)
    y = draw_line(c, "18", "Illinois income tax withheld (W-2s)", result.il_line_18_withheld, y)
    if result.il_estimated_payments > 0:
        y = draw_line(c, "19", "Estimated payments", result.il_estimated_payments, y)

    y -= 5
    il_total_payments = result.il_line_18_withheld + result.il_estimated_payments
    if result.il_refund > 0:
        y = draw_section(c, "Refund", y)
        y = draw_line(c, "20", "OVERPAYMENT (REFUND)", result.il_refund, y, bold=True)
    else:
        y = draw_section(c, "Amount You Owe", y)
        y = draw_line(c, "20", "AMOUNT YOU OWE", result.il_owed, y, bold=True)

    # Effective rate
    y -= 10
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.gray)
    c.drawString(58, y, f"Illinois flat tax rate: 4.95%")
    c.setFillColor(colors.black)

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Combined summary cover page
# ---------------------------------------------------------------------------
def generate_summary_page(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 40
    y = draw_header(c, "TaxLens", "Tax Return Summary", result.tax_year, y)
    y = draw_filer_info(c, result, y)

    # Federal summary
    y = draw_section(c, "Federal Tax Summary (Form 1040)", y)
    y = draw_line(c, "", "Total income", result.line_9_total_income, y)
    if result.sched_c_total_profit > 0:
        y = draw_line(c, "", "  Business income (Schedule C)", result.sched_c_total_profit, y)
    y = draw_line(c, "", "Adjusted gross income", result.line_11_agi, y)
    y = draw_line(c, "", f"Deduction ({result.deduction_type})", result.line_13_deduction, y)
    if result.qbi_deduction > 0:
        y = draw_line(c, "", "  QBI deduction (Section 199A)", result.qbi_deduction, y)
    y = draw_line(c, "", "Taxable income", result.line_15_taxable_income, y)
    if result.se_tax > 0:
        y = draw_line(c, "", "  Self-employment tax", result.se_tax, y)
    y = draw_line(c, "", "Total federal tax", result.line_24_total_tax, y, bold=True)
    y = draw_line(c, "", "Total withholding + payments", result.line_33_total_payments, y)
    if result.line_34_overpaid > 0:
        y = draw_line(c, "", "FEDERAL REFUND", result.line_34_overpaid, y, bold=True)
    else:
        y = draw_line(c, "", "FEDERAL AMOUNT OWED", result.line_37_owed, y, bold=True)

    # Illinois summary
    y -= 5
    y = draw_section(c, "Illinois Tax Summary (IL-1040)", y)
    y = draw_line(c, "", "Illinois base income", result.il_line_7_base_income, y)
    y = draw_line(c, "", "Personal exemptions", result.il_line_9_exemptions, y)
    y = draw_line(c, "", "Illinois taxable income", result.il_line_10_taxable, y)
    y = draw_line(c, "", "Illinois tax (4.95%)", result.il_line_11_tax, y, bold=True)
    y = draw_line(c, "", "State withholding + payments", result.il_line_18_withheld + result.il_estimated_payments, y)
    if result.il_refund > 0:
        y = draw_line(c, "", "ILLINOIS REFUND", result.il_refund, y, bold=True)
    else:
        y = draw_line(c, "", "ILLINOIS AMOUNT OWED", result.il_owed, y, bold=True)

    # Combined bottom line
    y -= 10
    y = draw_section(c, "Combined Bottom Line", y)
    net = result.line_34_overpaid + result.il_refund - result.line_37_owed - result.il_owed
    if net >= 0:
        y = draw_line(c, "", "NET TOTAL REFUND", net, y, bold=True)
    else:
        y = draw_line(c, "", "NET TOTAL OWED", abs(net), y, bold=True)

    # Effective rates
    y -= 15
    c.setFont("Helvetica", 8)
    if result.line_11_agi > 0:
        fed_eff = (result.line_24_total_tax / result.line_11_agi) * 100
        il_eff = (result.il_line_11_tax / result.line_11_agi) * 100
        combined = fed_eff + il_eff
        c.drawString(58, y, f"Effective rates — Federal: {fed_eff:.1f}%  |  Illinois: {il_eff:.1f}%  |  Combined: {combined:.1f}%")

    y -= 15
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")
    c.setFillColor(colors.black)

    # Forms included
    y -= 20
    c.setFont("Helvetica", 8)
    c.drawString(58, y, f"Forms generated: {', '.join(result.forms_generated)}")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Public API — generate all forms
# ---------------------------------------------------------------------------
def generate_all_pdfs(result: TaxResult, output_dir: str) -> dict:
    """Generate all tax form PDFs and save to output directory.

    Returns dict of form_name -> file_path.
    """
    from pathlib import Path
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    paths = {}

    # Summary cover page
    buf = generate_summary_page(result)
    p = out / "summary.pdf"
    p.write_bytes(buf.read())
    paths["summary"] = str(p)

    # Form 1040
    buf = generate_1040(result)
    p = out / "form_1040.pdf"
    p.write_bytes(buf.read())
    paths["1040"] = str(p)

    # Schedule C (if business income)
    if result.sched_c_businesses:
        buf = generate_schedule_c(result)
        p = out / "schedule_c.pdf"
        p.write_bytes(buf.read())
        paths["schedule_c"] = str(p)

    # Schedule SE (if self-employment tax)
    if result.se_tax > 0:
        buf = generate_schedule_se(result)
        p = out / "schedule_se.pdf"
        p.write_bytes(buf.read())
        paths["schedule_se"] = str(p)

    # Schedule A (if itemizing or always for reference)
    buf = generate_schedule_a(result)
    p = out / "schedule_a.pdf"
    p.write_bytes(buf.read())
    paths["schedule_a"] = str(p)

    # Schedule B (if significant interest/dividends)
    if result.sched_b_interest_total > 0 or result.sched_b_dividends_total > 0:
        buf = generate_schedule_b(result)
        p = out / "schedule_b.pdf"
        p.write_bytes(buf.read())
        paths["schedule_b"] = str(p)

    # Schedule D (if capital transactions)
    if result.capital_transactions:
        buf = generate_schedule_d(result)
        p = out / "schedule_d.pdf"
        p.write_bytes(buf.read())
        paths["schedule_d"] = str(p)

    # IL-1040
    buf = generate_il1040(result)
    p = out / "il_1040.pdf"
    p.write_bytes(buf.read())
    paths["il_1040"] = str(p)

    return paths
