"""PDF tax form generator — fills official IRS/IL fillable PDF templates.

Uses pypdf to populate actual government form fields with computed tax data.
Templates: IRS Form 1040, Schedules A/B/C/D/SE, IL-1040.
Keeps ReportLab summary page as a TaxLens-branded cover sheet.
"""

import copy
from io import BytesIO
from pathlib import Path
from typing import Optional

import pypdf
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors

from tax_engine import TaxResult

WIDTH, HEIGHT = letter
TEMPLATE_DIR = Path(__file__).parent / "templates"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _money(val: float) -> str:
    """Format a dollar value for IRS forms (no $ sign, round to whole)."""
    if val == 0:
        return ""
    return str(round(val))


def _money2(val: float) -> str:
    """Format with cents for specific fields."""
    if val == 0:
        return ""
    return f"{val:.2f}"


def _fill_pdf(template_path: str, field_map: dict) -> BytesIO:
    """Fill a PDF template and return as BytesIO.

    field_map: {field_name: value} — uses full dotted field names from pypdf.
    """
    reader = pypdf.PdfReader(template_path)
    writer = pypdf.PdfWriter(clone_from=reader)

    # Update form fields on each page
    for page_num in range(len(writer.pages)):
        writer.update_page_form_field_values(
            writer.pages[page_num], field_map, auto_regenerate=False
        )

    buf = BytesIO()
    writer.write(buf)
    buf.seek(0)
    return buf


def _set_checkbox(field_map: dict, field_name: str, checked: bool = True):
    """Set a checkbox field. IRS PDFs use /1 for checked, /Off for unchecked."""
    if checked:
        field_map[field_name] = "/1"


# ---------------------------------------------------------------------------
# ReportLab helpers (for summary page only)
# ---------------------------------------------------------------------------
def fmt(amount: float) -> str:
    if amount == 0:
        return "—"
    if amount < 0:
        return f"({abs(amount):,.2f})"
    return f"{amount:,.2f}"


def draw_header(c: canvas.Canvas, form_name: str, form_title: str, tax_year: int, y: float) -> float:
    c.setStrokeColor(colors.HexColor("#1a237e"))
    c.setLineWidth(2)
    c.line(50, y, WIDTH - 50, y)
    y -= 5
    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.HexColor("#1a237e"))
    c.drawString(55, y - 20, form_name)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(WIDTH / 2, y - 18, form_title)
    c.setFont("Helvetica-Bold", 14)
    c.drawRightString(WIDTH - 55, y - 20, str(tax_year))
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.gray)
    c.drawCentredString(WIDTH / 2, y - 30, "Generated by TaxLens — DRAFT for review purposes only")
    y -= 45
    c.setStrokeColor(colors.HexColor("#1a237e"))
    c.setLineWidth(1)
    c.line(50, y, WIDTH - 50, y)
    c.setFillColor(colors.black)
    return y - 10


def draw_section(c: canvas.Canvas, title: str, y: float) -> float:
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(colors.HexColor("#1a237e"))
    c.drawString(55, y, title)
    c.setLineWidth(0.5)
    c.setStrokeColor(colors.HexColor("#bbdefb"))
    c.line(55, y - 3, WIDTH - 55, y - 3)
    c.setFillColor(colors.black)
    return y - 16


def draw_line(c: canvas.Canvas, line_num: str, description: str, amount: float, y: float,
              bold: bool = False, indent: int = 0) -> float:
    font = "Helvetica-Bold" if bold else "Helvetica"
    c.setFont(font, 8)
    x_num = 58 + indent
    x_desc = 80 + indent
    x_amt = WIDTH - 60
    if line_num:
        c.setFillColor(colors.HexColor("#1a237e"))
        c.drawString(x_num, y, line_num)
    c.setFillColor(colors.black)
    c.drawString(x_desc, y, description)
    if bold:
        c.setStrokeColor(colors.HexColor("#1a237e"))
        c.setFillColor(colors.HexColor("#e8eaf6"))
        c.rect(x_amt - 80, y - 3, 130, 13, fill=1, stroke=1)
        c.setFillColor(colors.HexColor("#1a237e"))
    else:
        c.setStrokeColor(colors.HexColor("#e0e0e0"))
        c.rect(x_amt - 80, y - 3, 130, 13, fill=0, stroke=1)
        c.setFillColor(colors.black)
    c.setFont(font, 8)
    c.drawRightString(x_amt + 45, y, fmt(amount))
    c.setFillColor(colors.black)
    return y - 16


def draw_info_row(c: canvas.Canvas, label: str, value: str, y: float, x: float = 58) -> float:
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.gray)
    c.drawString(x, y, label)
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 9)
    c.drawString(x + 80, y, value)
    return y - 14


# ---------------------------------------------------------------------------
# Summary cover page (ReportLab — TaxLens branded)
# ---------------------------------------------------------------------------
def generate_summary_page(result: TaxResult) -> BytesIO:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "TaxLens", "Tax Return Summary", result.tax_year, y)

    # Filer info
    y = draw_section(c, "Filing Information", y)
    filer = result.filer
    status_labels = {"single": "Single", "mfj": "Married Filing Jointly",
                     "hoh": "Head of Household", "mfs": "Married Filing Separately"}
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    if result.filing_status == "mfj" and result.spouse:
        y = draw_info_row(c, "Spouse:", f"{result.spouse.first_name} {result.spouse.last_name}", y)
    if filer.address_street:
        y = draw_info_row(c, "Address:", filer.address_street, y)
        y = draw_info_row(c, "City/St/Zip:", f"{filer.address_city}, {filer.address_state} {filer.address_zip}", y)
    y = draw_info_row(c, "Filing Status:", status_labels.get(result.filing_status, result.filing_status), y)
    if result.num_dependents > 0:
        if result.dependents:
            dep_names = ", ".join(f"{d.first_name} {d.last_name}" for d in result.dependents if d.first_name)
            y = draw_info_row(c, "Dependents:", f"{result.num_dependents} — {dep_names}" if dep_names else str(result.num_dependents), y)
        else:
            y = draw_info_row(c, "Dependents:", str(result.num_dependents), y)
    y -= 5

    # Federal summary
    y = draw_section(c, "Federal Tax Summary (Form 1040)", y)
    y = draw_line(c, "", "Total income", result.line_9_total_income, y)
    if result.sched_c_total_profit > 0:
        y = draw_line(c, "", "  Business income (Schedule C)", result.sched_c_total_profit, y)
    y = draw_line(c, "", "Adjusted gross income", result.line_11_agi, y)
    y = draw_line(c, "", f"Deduction ({result.deduction_type})", result.line_13_deduction, y)
    if result.qbi_deduction > 0:
        y = draw_line(c, "", "  QBI deduction (Section 199A)", result.qbi_deduction, y)
    y = draw_line(c, "", "Taxable income", result.line_15_taxable_income, y)
    if result.se_tax > 0:
        y = draw_line(c, "", "  Self-employment tax", result.se_tax, y)
    if result.niit > 0:
        y = draw_line(c, "", "  Net Investment Income Tax (3.8%)", result.niit, y)
    if result.additional_medicare_tax > 0:
        y = draw_line(c, "", "  Additional Medicare Tax (0.9%)", result.additional_medicare_tax, y)
    y = draw_line(c, "", "Total federal tax", result.line_24_total_tax, y, bold=True)
    # Credits
    has_credits = (result.line_27_ctc > 0 or result.education_credit > 0 or
                   result.education_credit_refundable > 0 or result.cdcc > 0 or
                   result.savers_credit > 0 or result.eitc > 0)
    if has_credits:
        y = draw_section(c, "Credits", y)
        if result.line_27_ctc > 0:
            y = draw_line(c, "", "  Child Tax Credit", result.line_27_ctc, y)
        if result.education_credit > 0:
            y = draw_line(c, "", "  Education credits (nonrefundable)", result.education_credit, y)
        if result.education_credit_refundable > 0:
            y = draw_line(c, "", "  Education credits (refundable AOTC)", result.education_credit_refundable, y)
        if result.cdcc > 0:
            y = draw_line(c, "", "  Child & Dependent Care Credit", result.cdcc, y)
        if result.savers_credit > 0:
            y = draw_line(c, "", "  Saver's Credit", result.savers_credit, y)
        if result.eitc > 0:
            y = draw_line(c, "", "  Earned Income Tax Credit", result.eitc, y)

    if result.estimated_tax_penalty > 0:
        y = draw_line(c, "", "  Estimated tax penalty", result.estimated_tax_penalty, y)
    if result.amt > 0:
        y = draw_line(c, "", "  Alternative Minimum Tax", result.amt, y)

    y = draw_line(c, "", "Total withholding + payments", result.line_33_total_payments, y)
    if result.line_34_overpaid > 0:
        y = draw_line(c, "", "FEDERAL REFUND", result.line_34_overpaid, y, bold=True)
    else:
        y = draw_line(c, "", "FEDERAL AMOUNT OWED", result.line_37_owed, y, bold=True)

    # IL summary
    y -= 5
    y = draw_section(c, "Illinois Tax Summary (IL-1040)", y)
    y = draw_line(c, "", "Illinois base income", result.il_line_7_base_income, y)
    y = draw_line(c, "", "Personal exemptions", result.il_line_9_exemptions, y)
    y = draw_line(c, "", "Illinois taxable income", result.il_line_10_taxable, y)
    y = draw_line(c, "", "Illinois tax (4.95%)", result.il_line_11_tax, y, bold=True)
    il_payments = result.il_line_18_withheld + result.il_estimated_payments
    y = draw_line(c, "", "State withholding + payments", il_payments, y)
    if result.il_refund > 0:
        y = draw_line(c, "", "ILLINOIS REFUND", result.il_refund, y, bold=True)
    else:
        y = draw_line(c, "", "ILLINOIS AMOUNT OWED", result.il_owed, y, bold=True)

    # Combined
    y -= 10
    y = draw_section(c, "Combined Bottom Line", y)
    net = result.line_34_overpaid + result.il_refund - result.line_37_owed - result.il_owed
    if net >= 0:
        y = draw_line(c, "", "NET TOTAL REFUND", net, y, bold=True)
    else:
        y = draw_line(c, "", "NET TOTAL OWED", abs(net), y, bold=True)

    # Rates
    y -= 15
    c.setFont("Helvetica", 8)
    if result.line_11_agi > 0:
        fed_eff = (result.line_24_total_tax / result.line_11_agi) * 100
        il_eff = (result.il_line_11_tax / result.line_11_agi) * 100
        c.drawString(58, y, f"Effective rates — Federal: {fed_eff:.1f}%  |  Illinois: {il_eff:.1f}%  |  Combined: {fed_eff + il_eff:.1f}%")

    y -= 15
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")
    c.setFillColor(colors.black)
    y -= 20
    c.setFont("Helvetica", 8)
    c.drawString(58, y, f"Forms generated: {', '.join(result.forms_generated)}")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Form 1040 — Official IRS fillable PDF
# ---------------------------------------------------------------------------
def generate_1040(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040.pdf")
    f = {}
    filer = result.filer

    # Page 1 — Personal info
    p1 = "topmostSubform[0].Page1[0]."
    f[p1 + "f1_04[0]"] = f"{filer.first_name} {filer.last_name[0]}." if filer.last_name else filer.first_name
    f[p1 + "f1_05[0]"] = filer.last_name
    f[p1 + "f1_06[0]"] = filer.ssn

    if result.spouse and result.filing_status == "mfj":
        f[p1 + "f1_07[0]"] = f"{result.spouse.first_name} {result.spouse.last_name[0]}."
        f[p1 + "f1_08[0]"] = result.spouse.last_name
        f[p1 + "f1_09[0]"] = result.spouse.ssn

    # Address
    addr = p1 + "Address_ReadOrder[0]."
    f[addr + "f1_10[0]"] = filer.address_street
    f[addr + "f1_12[0]"] = filer.address_city
    f[addr + "f1_13[0]"] = filer.address_state
    f[addr + "f1_14[0]"] = filer.address_zip

    # Filing status checkboxes
    fs = p1 + "FilingStatus_ReadOrder[0]."
    if result.filing_status == "single":
        f[fs + "c1_3[0]"] = "/1"
    elif result.filing_status == "mfj":
        f[fs + "c1_3[1]"] = "/1"
    elif result.filing_status == "mfs":
        f[fs + "c1_3[2]"] = "/1"
    if result.filing_status == "hoh":
        f[p1 + "c1_3[0]"] = "/1"

    # Income lines
    f[p1 + "f1_32[0]"] = _money(result.line_1a_wages)             # Line 1a wages
    f[p1 + "f1_42[0]"] = _money(result.line_2a_tax_exempt_interest)  # Line 2a
    f[p1 + "f1_43[0]"] = _money(result.line_2b_taxable_interest)    # Line 2b
    f[p1 + "f1_44[0]"] = _money(result.line_3a_qualified_dividends) # Line 3a
    f[p1 + "f1_45[0]"] = _money(result.line_3b_ordinary_dividends)  # Line 3b

    # Line 4a-11 block
    l = p1 + "Line4a-11_ReadOrder[0]."
    f[l + "f1_52[0]"] = _money(result.line_7_capital_gain_loss)     # Line 7
    f[l + "f1_53[0]"] = _money(result.line_8_other_income + result.line_8a_business_income)  # Line 8
    f[l + "f1_54[0]"] = _money(result.line_9_total_income)          # Line 9
    f[l + "f1_55[0]"] = _money(result.line_10_adjustments)          # Line 10
    f[l + "f1_56[0]"] = _money(result.line_11_agi)                  # Line 11

    # Deductions
    f[p1 + "f1_57[0]"] = _money(result.line_13_deduction)           # Line 12/13
    f[p1 + "f1_58[0]"] = _money(result.qbi_deduction)               # Line 13 QBI
    total_deductions = result.line_13_deduction + result.qbi_deduction
    f[p1 + "f1_59[0]"] = _money(total_deductions)                   # Line 14
    f[p1 + "f1_60[0]"] = _money(result.line_15_taxable_income)      # Line 15

    # Page 2
    p2 = "topmostSubform[0].Page2[0]."
    f[p2 + "f2_02[0]"] = _money(result.line_16_tax + result.capital_gains_tax)  # Line 16
    # Schedule 2 taxes (NIIT + Additional Medicare) go on line 23
    sched2_tax = result.niit + result.additional_medicare_tax
    if sched2_tax > 0:
        f[p2 + "f2_09[0]"] = _money(sched2_tax)                     # Line 23
    f[p2 + "f2_10[0]"] = _money(result.line_24_total_tax)           # Line 24

    f[p2 + "f2_11[0]"] = _money(result.line_25_federal_withheld)    # Line 25a
    f[p2 + "f2_14[0]"] = _money(result.line_25_federal_withheld)    # Line 25d total
    if result.estimated_payments > 0:
        f[p2 + "f2_15[0]"] = _money(result.estimated_payments)      # Line 26
    if result.line_27_ctc > 0:
        f[p2 + "f2_05[0]"] = _money(result.line_27_ctc)             # Line 19 CTC
    f[p2 + "f2_22[0]"] = _money(result.line_33_total_payments)      # Line 33

    if result.line_34_overpaid > 0:
        f[p2 + "f2_23[0]"] = _money(result.line_34_overpaid)        # Line 34
        f[p2 + "f2_24[0]"] = _money(result.line_34_overpaid)        # Line 35a
    if result.line_37_owed > 0:
        f[p2 + "f2_28[0]"] = _money(result.line_37_owed)            # Line 37

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Schedule A — Itemized Deductions
# ---------------------------------------------------------------------------
def generate_schedule_a(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040sa.pdf")
    f = {}
    p1 = "form1[0].Page1[0]."
    filer = result.filer

    f[p1 + "f1_1[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p1 + "f1_2[0]"] = filer.ssn

    # Medical (lines 1-4)
    if result.sched_a_medical > 0:
        raw_medical = result.sched_a_medical + result.line_11_agi * 0.075
        f[p1 + "f1_3[0]"] = _money(raw_medical)                     # Line 1
        f[p1 + "f1_5[0]"] = _money(result.line_11_agi)              # Line 2 AGI
        f[p1 + "f1_6[0]"] = _money(result.line_11_agi * 0.075)      # Line 3
        f[p1 + "f1_7[0]"] = _money(result.sched_a_medical)          # Line 4

    # SALT (lines 5-7)
    f[p1 + "f1_11[0]"] = _money(result.sched_a_salt)                # Line 5d/7

    # Mortgage interest (line 8a)
    f[p1 + "f1_13[0]"] = _money(result.sched_a_mortgage_interest)   # Line 8a
    f[p1 + "Line8b_ReadOrder[0].f1_16[0]"] = _money(result.sched_a_mortgage_interest)  # Line 10

    # Charitable (lines 12-14)
    f[p1 + "f1_19[0]"] = _money(result.sched_a_charitable)          # Line 12
    f[p1 + "f1_22[0]"] = _money(result.sched_a_charitable)          # Line 14

    # Total (line 17)
    f[p1 + "f1_27[0]"] = _money(result.sched_a_total)               # Line 17

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Schedule B — Interest and Ordinary Dividends
# ---------------------------------------------------------------------------
def generate_schedule_b(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040sb.pdf")
    f = {}
    p1 = "topmostSubform[0].Page1[0]."
    filer = result.filer

    f[p1 + "f1_01[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p1 + "f1_02[0]"] = filer.ssn

    # Interest - Line 1 (payer + amount)
    if result.sched_b_interest_total > 0:
        f[p1 + "Line1_ReadOrder[0].f1_03[0]"] = "Various (from 1099-INT/OCR)"
        f[p1 + "f1_04[0]"] = _money(result.sched_b_interest_total)
    # Line 4 total interest
    f[p1 + "f1_31[0]"] = _money(result.sched_b_interest_total)
    f[p1 + "f1_33[0]"] = _money(result.sched_b_interest_total)

    # Dividends - Part II
    if result.sched_b_dividends_total > 0:
        f[p1 + "f1_35[0]"] = "Various payers"
        f[p1 + "f1_36[0]"] = _money(result.sched_b_dividends_total)
    # Line 6 total dividends
    f[p1 + "f1_63[0]"] = _money(result.sched_b_dividends_total) if hasattr(result, 'sched_b_dividends_total') else ""

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Schedule C — Profit or Loss from Business
# ---------------------------------------------------------------------------
def generate_schedule_c(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040sc.pdf")
    f = {}
    p1 = "topmostSubform[0].Page1[0]."
    filer = result.filer

    f[p1 + "f1_1[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p1 + "f1_2[0]"] = filer.ssn

    # Use the first business for the main form
    biz_list = result.businesses or []
    if biz_list:
        biz = biz_list[0]
        f[p1 + "f1_3[0]"] = biz.business_name                      # Line A
        f[p1 + "BComb[0].f1_4[0]"] = biz.business_type              # Line B
        if biz.ein:
            f[p1 + "DComb[0].f1_6[0]"] = biz.ein                    # Line D

    # Use totals across all businesses
    total_gross = sum(b.gross_receipts for b in biz_list)
    total_cogs = sum(b.cost_of_goods_sold for b in biz_list)
    total_gross_profit = sum(b.gross_profit for b in biz_list)
    total_expenses = sum(b.total_expenses for b in biz_list)
    total_net = sum(b.net_profit for b in biz_list)

    f[p1 + "f1_8[0]"] = _money(total_gross)                         # Line 1 gross receipts
    f[p1 + "f1_11[0]"] = _money(total_gross)                        # Line 3
    f[p1 + "f1_12[0]"] = _money(total_cogs)                         # Line 4 COGS
    f[p1 + "f1_13[0]"] = _money(total_gross_profit)                  # Line 5 gross profit
    f[p1 + "f1_14[0]"] = _money(total_gross_profit)                  # Line 7

    # Expenses (lines 8-27)
    lines = p1 + "Lines8-17[0]."
    total_adv = sum(b.advertising for b in biz_list)
    total_car = sum(b.car_expenses for b in biz_list)
    total_ins = sum(b.insurance for b in biz_list)
    total_office = sum(b.office_expense for b in biz_list)
    total_rent = sum(b.rent for b in biz_list)
    total_supplies = sum(b.supplies for b in biz_list)
    total_util = sum(b.utilities for b in biz_list)
    total_other = sum(b.other_expenses for b in biz_list)

    f[lines + "f1_17[0]"] = _money(total_adv)                       # Line 8  advertising
    f[lines + "f1_18[0]"] = _money(total_car)                       # Line 9  car
    f[lines + "f1_22[0]"] = _money(total_ins)                       # Line 15 insurance
    f[lines + "f1_25[0]"] = _money(total_office)                    # Line 18 office
    lines2 = p1 + "Lines18-27[0]."
    f[lines2 + "f1_29[0]"] = _money(total_rent)                     # Line 20b rent
    f[lines2 + "f1_32[0]"] = _money(total_supplies)                 # Line 22 supplies
    f[lines2 + "f1_36[0]"] = _money(total_util)                     # Line 25 utilities
    f[lines2 + "f1_38[0]"] = _money(total_other)                    # Line 27a other

    # Home office deduction (Line 30)
    total_home_office = 0.0
    for b in biz_list:
        if b.home_total_sqft > 0 and b.home_office_sqft > 0:
            total_home_office += b.home_expenses * (b.home_office_sqft / b.home_total_sqft)
    if total_home_office > 0:
        f[p1 + "f1_40[0]"] = _money(total_home_office)              # Line 30 home office

    # Totals
    f[p1 + "f1_41[0]"] = _money(total_expenses)                     # Line 28
    f[p1 + "f1_42[0]"] = _money(total_net)                          # Line 31 net profit

    # If multiple businesses, add note
    if len(biz_list) > 1:
        desc_parts = [f"{b.business_name}: ${b.net_profit:,.0f}" for b in biz_list]
        f[lines2 + "f1_39[0]"] = "; ".join(desc_parts)              # Line 27b description

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Schedule D — Capital Gains and Losses
# ---------------------------------------------------------------------------
def generate_schedule_d(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040sd.pdf")
    f = {}
    p1 = "topmostSubform[0].Page1[0]."
    filer = result.filer

    f[p1 + "f1_1[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p1 + "f1_2[0]"] = filer.ssn

    # Part I — Short-term (rows 1a-3, then line 7)
    short_txns = [t for t in result.capital_transactions if not t.is_long_term]
    for i, t in enumerate(short_txns[:3]):
        row_base = f"Table_PartI[0].Row{['1a','1b','2'][i]}[0]."
        idx_start = 3 + i * 4
        f[p1 + row_base + f"f1_{idx_start}[0]"] = t.description
        f[p1 + row_base + f"f1_{idx_start+1}[0]"] = t.date_acquired
        f[p1 + row_base + f"f1_{idx_start+2}[0]"] = t.date_sold
        f[p1 + row_base + f"f1_{idx_start+3}[0]"] = _money(t.proceeds)
        # Cost basis and gain in adjacent columns
        f[p1 + row_base + f"f1_{idx_start+4}[0]"] = _money(t.cost_basis)
        f[p1 + row_base + f"f1_{idx_start+6}[0]"] = _money(t.gain_loss)
    f[p1 + "f1_19[0]"] = _money(result.sched_d_short_term_gain)     # Line 7

    # Part II — Long-term (rows 8a-10, then line 15)
    long_txns = [t for t in result.capital_transactions if t.is_long_term]
    for i, t in enumerate(long_txns[:3]):
        row_base = f"Table_PartII[0].Row{['8a','8b','9'][i]}[0]."
        idx_start = 23 + i * 4
        f[p1 + row_base + f"f1_{idx_start}[0]"] = t.description
        f[p1 + row_base + f"f1_{idx_start+1}[0]"] = t.date_acquired
        f[p1 + row_base + f"f1_{idx_start+2}[0]"] = t.date_sold
        f[p1 + row_base + f"f1_{idx_start+3}[0]"] = _money(t.proceeds)
        f[p1 + row_base + f"f1_{idx_start+4}[0]"] = _money(t.cost_basis)
        f[p1 + row_base + f"f1_{idx_start+6}[0]"] = _money(t.gain_loss)
    f[p1 + "f1_39[0]"] = _money(result.sched_d_long_term_gain)      # Line 15

    # Part III
    f[p1 + "f1_43[0]"] = _money(result.sched_d_net_gain)            # Line 16

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Schedule SE — Self-Employment Tax
# ---------------------------------------------------------------------------
def generate_schedule_se(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040sse.pdf")
    f = {}
    p1 = "topmostSubform[0].Page1[0]."
    filer = result.filer

    f[p1 + "f1_1[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p1 + "f1_2[0]"] = filer.ssn

    # Short Schedule SE
    f[p1 + "f1_3[0]"] = _money(result.sched_se_net_earnings)        # Line 2
    f[p1 + "f1_4[0]"] = _money(result.sched_se_taxable)             # Line 3 (92.35%)
    f[p1 + "f1_5[0]"] = _money(result.sched_se_taxable)             # Line 4a

    # Line 4b SS wages from W-2
    w2_ss = sum(w.ss_wages for w in result.w2s)
    if w2_ss > 0:
        f[p1 + "f1_7[0]"] = _money(w2_ss)                           # Line 4b
    f[p1 + "f1_9[0]"] = _money(result.sched_se_ss_tax)              # Line 5a/6 SS tax
    f[p1 + "f1_12[0]"] = _money(result.sched_se_total)              # Line 12 total SE tax
    f[p1 + "f1_13[0]"] = _money(result.se_tax_deduction)            # Line 13 (50% deduction)

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Schedule 2 — Additional Taxes
# ---------------------------------------------------------------------------
def generate_schedule_2(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f1040s2.pdf")
    f = {}
    p1 = "form1[0].Page1[0]."
    p2 = "form1[0].Page2[0]."
    filer = result.filer

    f[p1 + "f1_01[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p1 + "f1_02[0]"] = filer.ssn

    # Line 4: Self-employment tax (from Schedule SE)
    if result.se_tax > 0:
        f[p1 + "f1_15[0]"] = _money(result.se_tax)

    # Line 11: Additional Medicare Tax (Form 8959)
    if result.additional_medicare_tax > 0:
        f[p1 + "f1_22[0]"] = _money(result.additional_medicare_tax)

    # Line 12: Net investment income tax (Form 8960)
    if result.niit > 0:
        f[p1 + "f1_23[0]"] = _money(result.niit)

    # Line 21: Total other taxes (line 4 + lines 7-16 + 18 + 19)
    # For us: SE tax + Additional Medicare + NIIT
    total_other = result.se_tax + result.additional_medicare_tax + result.niit
    f[p2 + "f2_24[0]"] = _money(total_other)

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Form 8959 — Additional Medicare Tax
# ---------------------------------------------------------------------------
def generate_form_8959(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f8959.pdf")
    f = {}
    p = "topmostSubform[0].Page1[0]."
    filer = result.filer

    f[p + "f1_1[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p + "f1_2[0]"] = filer.ssn

    # Part I — Additional Medicare Tax on Medicare Wages
    medicare_wages = sum(w.medicare_wages for w in result.w2s)
    f[p + "f1_3[0]"] = _money(medicare_wages)                    # Line 1
    # Lines 2-3 (unreported tips, Form 8919) — skip
    f[p + "f1_6[0]"] = _money(medicare_wages)                    # Line 4 (= line 1 for us)

    from tax_config import ADDITIONAL_MEDICARE_THRESHOLD
    threshold = ADDITIONAL_MEDICARE_THRESHOLD[result.filing_status]
    f[p + "f1_7[0]"] = _money(threshold)                         # Line 5

    wage_excess = max(0, medicare_wages - threshold)
    f[p + "f1_8[0]"] = _money(wage_excess)                       # Line 6

    wage_tax = wage_excess * 0.009
    f[p + "f1_9[0]"] = _money(wage_tax)                          # Line 7

    # Part II — Additional Medicare Tax on Self-Employment Income
    se_income = result.sched_se_taxable
    f[p + "f1_10[0]"] = _money(se_income)                        # Line 8

    # Line 9: threshold for SE = threshold - line 4 wages (not below 0)
    reduced_threshold = max(0, threshold - medicare_wages)
    f[p + "f1_11[0]"] = _money(reduced_threshold)                # Line 9
    f[p + "f1_12[0]"] = _money(medicare_wages)                   # Line 10 (= line 4)

    se_excess = max(0, se_income - reduced_threshold)
    f[p + "f1_13[0]"] = _money(se_excess)                        # Line 11 (line 9 from line 8... wait)

    # Actually: Line 11 = line 10 subtracted from line 9
    # Line 10 = amount from line 4 (medicare wages)
    # Line 11 = line 9 - line 10 (reduced threshold)
    # Line 12 = line 8 - line 11, if > 0
    remaining_threshold = max(0, threshold - medicare_wages)
    se_taxable_excess = max(0, se_income - remaining_threshold)
    f[p + "f1_13[0]"] = _money(remaining_threshold)              # Line 11
    f[p + "f1_14[0]"] = _money(se_taxable_excess)                # Line 12

    se_tax_8959 = se_taxable_excess * 0.009
    f[p + "f1_15[0]"] = _money(se_tax_8959)                      # Line 13

    # Part III — RRTA (skip, lines 14-17)

    # Part IV — Total Additional Medicare Tax
    total_add_medicare = wage_tax + se_tax_8959
    f[p + "f1_20[0]"] = _money(total_add_medicare)               # Line 18

    # Part V — Withholding Reconciliation
    medicare_withheld = sum(w.medicare_withheld for w in result.w2s)
    f[p + "f1_21[0]"] = _money(medicare_withheld)                # Line 19
    f[p + "f1_22[0]"] = _money(medicare_wages)                   # Line 20
    regular_medicare = medicare_wages * 0.0145
    f[p + "f1_23[0]"] = _money(regular_medicare)                 # Line 21
    excess_withholding = max(0, medicare_withheld - regular_medicare)
    f[p + "f1_24[0]"] = _money(excess_withholding)               # Line 22
    # Line 23 RRTA — skip
    f[p + "f1_26[0]"] = _money(excess_withholding)               # Line 24

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# Form 8960 — Net Investment Income Tax
# ---------------------------------------------------------------------------
def generate_form_8960(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "f8960.pdf")
    f = {}
    p = "topmostSubform[0].Page1[0]."
    filer = result.filer

    f[p + "f1_1[0]"] = f"{filer.first_name} {filer.last_name}"
    f[p + "f1_2[0]"] = filer.ssn

    # Part I — Investment Income
    f[p + "f1_3[0]"] = _money(result.line_2b_taxable_interest)   # Line 1 (interest)
    f[p + "f1_4[0]"] = _money(result.line_3b_ordinary_dividends) # Line 2 (dividends)
    # Lines 3 (annuities), 4a-4c (rental/partnerships) — skip

    # Line 5a: Net gain from disposition of property (capital gains)
    net_cap_gain = max(0, result.sched_d_net_gain)
    f[p + "f1_9[0]"] = _money(net_cap_gain)                      # Line 5a
    f[p + "f1_12[0]"] = _money(net_cap_gain)                     # Line 5d (= 5a for us)

    # Line 8: Total investment income
    total_investment = (
        result.line_2b_taxable_interest
        + result.line_3b_ordinary_dividends
        + net_cap_gain
    )
    f[p + "f1_15[0]"] = _money(total_investment)                  # Line 8

    # Part II — Investment Expenses (skip, lines 9-11)

    # Part III — Tax Computation
    f[p + "f1_22[0]"] = _money(total_investment)                  # Line 12 (net investment income)

    from tax_config import NIIT_THRESHOLD
    threshold = NIIT_THRESHOLD[result.filing_status]
    f[p + "f1_23[0]"] = _money(result.line_11_agi)               # Line 13 (MAGI = AGI)
    f[p + "f1_24[0]"] = _money(threshold)                        # Line 14 (threshold)

    agi_excess = max(0, result.line_11_agi - threshold)
    f[p + "f1_25[0]"] = _money(agi_excess)                       # Line 15

    niit_base = min(total_investment, agi_excess)
    f[p + "f1_26[0]"] = _money(niit_base)                        # Line 16

    f[p + "f1_27[0]"] = _money(result.niit)                      # Line 17 (NIIT)

    return _fill_pdf(template, f)


# ---------------------------------------------------------------------------
# IL-1040 — Illinois Individual Income Tax Return
# ---------------------------------------------------------------------------
def generate_il1040(result: TaxResult) -> BytesIO:
    template = str(TEMPLATE_DIR / "il1040.pdf")
    f = {}
    filer = result.filer

    # Filer info
    f["step1-A-firstnamemi"] = f"{filer.first_name} {filer.last_name[0]}." if filer.last_name else filer.first_name
    f["step1-A-lastname"] = filer.last_name
    f["step1-A-ssn"] = filer.ssn
    f["step1-A-mailingaddress"] = filer.address_street
    f["step1-A-city"] = filer.address_city
    f["step1-A-state"] = filer.address_state
    f["step1-A-zip"] = filer.address_zip

    if result.spouse and result.filing_status == "mfj":
        f["step1-A-spousefirstnamemi"] = f"{result.spouse.first_name} {result.spouse.last_name[0]}."
        f["step1-A-spouselastname"] = result.spouse.last_name
        f["step1-A-spousessn"] = result.spouse.ssn

    # Income lines
    f["Federally adjusted income"] = _money(result.il_line_1_federal_agi)    # Line 1
    f["Other additions"] = _money(result.il_line_3_additions)                # Line 3
    f["Total income"] = _money(result.il_line_7_base_income)                 # Line 7
    f["Illinois base income"] = _money(result.il_line_7_base_income)         # Line 9

    # Exemptions
    num_ex = 1
    if result.filing_status == "mfj" and result.spouse:
        num_ex = 2
    num_ex += result.num_dependents
    f["Exemption allowance"] = _money(result.il_line_9_exemptions)           # Line 10
    f["Claiming dependents"] = str(num_ex)

    # Tax
    f["Illinois net income from Schedule NR"] = _money(result.il_line_10_taxable)  # Net income
    f["Income tax"] = _money(result.il_line_11_tax)                          # Line 14

    # Tax after credits
    f["Tax after nonrefundable credits"] = _money(result.il_line_11_tax)
    f["Total Tax"] = _money(result.il_line_11_tax)
    f["Total tax from Page 1"] = _money(result.il_line_11_tax)

    # Payments
    f["Illinois Income Tax withheld"] = _money(result.il_line_18_withheld)
    if result.il_estimated_payments > 0:
        f["Estimated payments"] = _money(result.il_estimated_payments)

    total_payments = result.il_line_18_withheld + result.il_estimated_payments
    f["Total payments and refundable credit"] = _money(total_payments)

    if result.il_refund > 0:
        f["If Line 31 is greater"] = _money(result.il_refund)
        f["Overpayment amount"] = _money(result.il_refund)
        f["Refunded to you"] = _money(result.il_refund)
    elif result.il_owed > 0:
        f["If Line 24 is greater"] = _money(result.il_owed)
        f["Amount you owe"] = _money(result.il_owed)

    return _fill_pdf(template, f)


def generate_generic_state_summary(state_result) -> BytesIO:
    """Generate a ReportLab summary page for states without official fillable PDFs."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)

    y = HEIGHT - 1 * inch
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, y, f"{state_result.state_name} State Tax Return")
    y -= 0.3 * inch
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, y, f"Form: {state_result.form_name or 'N/A'}  |  "
                               f"Return type: {state_result.return_type.title()}")
    y -= 0.5 * inch

    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Income")
    y -= 0.25 * inch
    c.setFont("Helvetica", 10)
    lines = [
        ("Federal AGI", state_result.federal_agi),
        ("Additions", state_result.additions),
        ("Base Income", state_result.base_income),
    ]
    if state_result.return_type == "nonresident":
        lines.append(("Allocated Income", state_result.allocated_income))
        lines.append(("Allocation %", f"{state_result.allocation_pct:.1%}"))
    lines += [
        ("Exemptions", state_result.exemptions),
        ("Standard Deduction", state_result.standard_deduction_amount),
        ("Taxable Income", state_result.taxable_income),
    ]
    for label, val in lines:
        if isinstance(val, str):
            c.drawString(1.2 * inch, y, f"{label}:")
            c.drawRightString(5.5 * inch, y, val)
        else:
            c.drawString(1.2 * inch, y, f"{label}:")
            c.drawRightString(5.5 * inch, y, f"${val:,.2f}")
        y -= 0.2 * inch

    y -= 0.15 * inch
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Tax")
    y -= 0.25 * inch
    c.setFont("Helvetica", 10)
    tax_lines = [
        ("State Tax", state_result.tax),
        ("Surtax", state_result.surtax),
        ("Total Tax", state_result.total_tax),
    ]
    for label, val in tax_lines:
        c.drawString(1.2 * inch, y, f"{label}:")
        c.drawRightString(5.5 * inch, y, f"${val:,.2f}")
        y -= 0.2 * inch

    y -= 0.15 * inch
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Payments & Credits")
    y -= 0.25 * inch
    c.setFont("Helvetica", 10)
    pay_lines = [
        ("Withholding", state_result.withholding),
        ("Estimated Payments", state_result.estimated_payments),
        ("Credit for Other States", state_result.credit_for_other_states),
    ]
    for label, val in pay_lines:
        c.drawString(1.2 * inch, y, f"{label}:")
        c.drawRightString(5.5 * inch, y, f"${val:,.2f}")
        y -= 0.2 * inch

    y -= 0.15 * inch
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Bottom Line")
    y -= 0.25 * inch
    c.setFont("Helvetica", 10)
    if state_result.refund > 0:
        c.setFillColor(colors.darkgreen)
        c.drawString(1.2 * inch, y, "REFUND:")
        c.drawRightString(5.5 * inch, y, f"${state_result.refund:,.2f}")
    elif state_result.owed > 0:
        c.setFillColor(colors.red)
        c.drawString(1.2 * inch, y, "AMOUNT OWED:")
        c.drawRightString(5.5 * inch, y, f"${state_result.owed:,.2f}")
    else:
        c.drawString(1.2 * inch, y, "No tax due")

    c.setFillColor(colors.black)
    y -= 0.5 * inch
    c.setFont("Helvetica", 8)
    c.drawString(1 * inch, y, "Generated by TaxLens — for estimation purposes only. "
                               "File official state return via state tax authority.")

    c.save()
    buf.seek(0)
    return buf


# States with fillable PDF templates
_STATE_TEMPLATE_MAP = {
    "IL": ("il1040.pdf", "generate_il1040"),
}


# ---------------------------------------------------------------------------
# Form 6251 — Alternative Minimum Tax (ReportLab)
# ---------------------------------------------------------------------------
def generate_form_6251(result: TaxResult) -> BytesIO:
    """Generate Form 6251 (AMT) summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Form 6251", "Alternative Minimum Tax — Individuals", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y -= 5

    y = draw_section(c, "Part I — Alternative Minimum Taxable Income", y)
    y = draw_line(c, "1", "Taxable income (Form 1040, line 15)", result.line_15_taxable_income, y)
    salt_addback = result.sched_a_salt if result.deduction_type == "itemized" else 0
    y = draw_line(c, "2a", "State/local tax deduction add-back (SALT)", salt_addback, y)
    y = draw_line(c, "28", "Alternative minimum taxable income (AMTI)", result.amt_income, y, bold=True)
    y -= 5

    y = draw_section(c, "Part II — AMT Exemption & Tax", y)
    y = draw_line(c, "29", "Exemption amount", result.amt_exemption, y)
    amt_taxable = max(0, result.amt_income - result.amt_exemption)
    y = draw_line(c, "30", "AMTI minus exemption", amt_taxable, y)
    y = draw_line(c, "31", "Tentative minimum tax", result.amt_tentative, y)
    regular_tax = result.line_16_tax + result.capital_gains_tax
    y = draw_line(c, "32", "Regular tax (before credits)", regular_tax, y)
    y = draw_line(c, "33", "AMT (excess of tentative over regular)", result.amt, y, bold=True)

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Form 8863 — Education Credits (AOTC + LLC) (ReportLab)
# ---------------------------------------------------------------------------
def generate_form_8863(result: TaxResult) -> BytesIO:
    """Generate Form 8863 (Education Credits) summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Form 8863", "Education Credits (AOTC and LLC)", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y -= 5

    y = draw_section(c, "Part I — Refundable American Opportunity Credit", y)
    y = draw_line(c, "1", "Tentative AOTC (refundable portion — 40%)", result.education_credit_refundable, y)
    y = draw_line(c, "", "Refundable credit to Form 1040", result.education_credit_refundable, y, bold=True)
    y -= 5

    y = draw_section(c, "Part II — Nonrefundable Education Credits", y)
    y = draw_line(c, "19", "Nonrefundable credit (AOTC 60% + LLC)", result.education_credit, y, bold=True)
    y -= 5

    total_ed = result.education_credit + result.education_credit_refundable
    y = draw_section(c, "Total Education Credit Benefit", y)
    y = draw_line(c, "", "Total education credits", total_ed, y, bold=True)

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Schedule EIC — Earned Income Credit (ReportLab)
# ---------------------------------------------------------------------------
def generate_schedule_eic(result: TaxResult) -> BytesIO:
    """Generate Schedule EIC summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Schedule EIC", "Earned Income Credit", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y = draw_info_row(c, "Filing Status:", result.filing_status, y)
    y -= 5

    y = draw_section(c, "Earned Income Credit Computation", y)
    y = draw_line(c, "", "Earned income (wages + SE)", result.eitc_earned_income, y)
    y = draw_line(c, "", "Adjusted Gross Income", result.line_11_agi, y)
    num_children = min(result.num_dependents, 3)
    y = draw_line(c, "", "Number of qualifying children", float(num_children), y)
    y = draw_line(c, "", "Earned Income Credit", result.eitc, y, bold=True)

    y -= 10
    c.setFont("Helvetica", 8)
    c.drawString(58, y, "This credit is fully refundable and added to Form 1040 payments.")

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Form 2441 — Child and Dependent Care Expenses (ReportLab)
# ---------------------------------------------------------------------------
def generate_form_2441(result: TaxResult) -> BytesIO:
    """Generate Form 2441 (CDCC) summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Form 2441", "Child and Dependent Care Expenses", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y -= 5

    y = draw_section(c, "Part III — Dependent Care Credit", y)
    y = draw_line(c, "", "Adjusted Gross Income", result.line_11_agi, y)

    from tax_config import CDCC_RATE_START_AGI, CDCC_MAX_RATE, CDCC_RATE_STEP_AGI, CDCC_MIN_RATE
    if result.line_11_agi <= CDCC_RATE_START_AGI:
        rate = CDCC_MAX_RATE
    else:
        steps = int((result.line_11_agi - CDCC_RATE_START_AGI) / CDCC_RATE_STEP_AGI)
        rate = max(CDCC_MIN_RATE, CDCC_MAX_RATE - steps * 0.01)
    c.setFont("Helvetica", 8)
    y -= 2
    c.drawString(80, y, f"Credit rate based on AGI: {rate:.0%}")
    y -= 16

    y = draw_line(c, "", "Child and Dependent Care Credit", result.cdcc, y, bold=True)

    y -= 10
    c.setFont("Helvetica", 8)
    c.drawString(58, y, "This credit is nonrefundable — limited to tax liability after other credits.")

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Form 8880 — Credit for Qualified Retirement Savings (ReportLab)
# ---------------------------------------------------------------------------
def generate_form_8880(result: TaxResult) -> BytesIO:
    """Generate Form 8880 (Saver's Credit) summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Form 8880", "Credit for Qualified Retirement Savings Contributions", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y -= 5

    y = draw_section(c, "Saver's Credit Computation", y)
    y = draw_line(c, "", "Adjusted Gross Income", result.line_11_agi, y)

    from tax_config import SAVERS_AGI_TIERS, SINGLE
    tiers = SAVERS_AGI_TIERS.get(result.filing_status, SAVERS_AGI_TIERS[SINGLE])
    if result.line_11_agi <= tiers[0]:
        rate_str = "50%"
    elif result.line_11_agi <= tiers[1]:
        rate_str = "20%"
    elif result.line_11_agi <= tiers[2]:
        rate_str = "10%"
    else:
        rate_str = "0%"
    c.setFont("Helvetica", 8)
    y -= 2
    c.drawString(80, y, f"Credit rate based on AGI: {rate_str}")
    y -= 16

    y = draw_line(c, "", "Retirement Savings Credit", result.savers_credit, y, bold=True)

    y -= 10
    c.setFont("Helvetica", 8)
    c.drawString(58, y, "This credit is nonrefundable — limited to tax liability after other credits.")

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Form 2210 — Underpayment of Estimated Tax (ReportLab)
# ---------------------------------------------------------------------------
def generate_form_2210(result: TaxResult) -> BytesIO:
    """Generate Form 2210 (Estimated Tax Penalty) summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Form 2210", "Underpayment of Estimated Tax by Individuals", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y -= 5

    y = draw_section(c, "Short Method — Penalty Computation", y)
    y = draw_line(c, "1", "Required annual payment", result.estimated_tax_required, y)
    total_paid = result.line_25_federal_withheld + result.estimated_payments
    y = draw_line(c, "2", "Withholding + estimated payments", total_paid, y)
    underpayment = max(0, result.estimated_tax_required - total_paid)
    y = draw_line(c, "3", "Underpayment", underpayment, y)

    from tax_config import ESTIMATED_TAX_PENALTY_RATE
    c.setFont("Helvetica", 8)
    y -= 2
    c.drawString(80, y, f"Penalty rate: {ESTIMATED_TAX_PENALTY_RATE:.0%} per year")
    y -= 16

    y = draw_line(c, "15", "Estimated tax penalty", result.estimated_tax_penalty, y, bold=True)

    y -= 10
    c.setFont("Helvetica", 8)
    c.drawString(58, y, "Penalty is added to amount owed on Form 1040, line 38.")

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Form 8889 — Health Savings Accounts (ReportLab)
# ---------------------------------------------------------------------------
def generate_form_8889(result: TaxResult) -> BytesIO:
    """Generate Form 8889 (HSA) summary via ReportLab."""
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = HEIGHT - 40
    y = draw_header(c, "Form 8889", "Health Savings Accounts (HSAs)", result.tax_year, y)

    filer = result.filer
    y = draw_info_row(c, "Name:", f"{filer.first_name} {filer.last_name}", y)
    y = draw_info_row(c, "SSN:", filer.ssn, y)
    y -= 5

    y = draw_section(c, "Part I — HSA Contributions and Deduction", y)
    y = draw_line(c, "2", "HSA contributions you made (personal)", result.form_8889_contributions, y)
    y = draw_line(c, "7", "Contribution limit", result.form_8889_limit, y)
    y = draw_line(c, "9", "Employer contributions (incl. cafeteria plan)", result.form_8889_employer, y)

    line_10 = max(0, result.form_8889_limit - result.form_8889_employer)
    y = draw_line(c, "10", "Maximum deductible (limit minus employer)", line_10, y)
    y = draw_line(c, "13", "HSA deduction (Line 25 of Schedule 1)", result.form_8889_deduction, y, bold=True)

    if result.form_8889_excess > 0:
        y -= 5
        y = draw_section(c, "Excess Contributions", y)
        y = draw_line(c, "", "Excess contributions (subject to 6% excise)", result.form_8889_excess, y)
        c.setFont("Helvetica", 8)
        y -= 2
        c.drawString(80, y, "See Form 5329, Part VII for the 6% additional tax on excess contributions.")
        y -= 16

    y -= 10
    c.setFont("Helvetica", 8)
    c.drawString(58, y, "Form 8889 is required for any year you have an HSA or make/receive HSA contributions.")

    y -= 20
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(colors.HexColor("#c62828"))
    c.drawString(58, y, "DRAFT — FOR REVIEW ONLY — NOT FOR FILING")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf


# ---------------------------------------------------------------------------
# Public API — generate all forms
# ---------------------------------------------------------------------------
def generate_all_pdfs(result: TaxResult, output_dir: str) -> dict:
    """Generate all tax form PDFs and save to output directory."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths = {}

    # Summary cover page (ReportLab branded)
    buf = generate_summary_page(result)
    p = out / "summary.pdf"
    p.write_bytes(buf.read())
    paths["summary"] = str(p)

    # Form 1040 (official IRS template)
    buf = generate_1040(result)
    p = out / "form_1040.pdf"
    p.write_bytes(buf.read())
    paths["1040"] = str(p)

    # Schedule C (if business income)
    if result.sched_c_businesses:
        buf = generate_schedule_c(result)
        p = out / "schedule_c.pdf"
        p.write_bytes(buf.read())
        paths["schedule_c"] = str(p)

    # Schedule SE (if self-employment tax)
    if result.se_tax > 0:
        buf = generate_schedule_se(result)
        p = out / "schedule_se.pdf"
        p.write_bytes(buf.read())
        paths["schedule_se"] = str(p)

    # Schedule A (if itemizing or for reference)
    buf = generate_schedule_a(result)
    p = out / "schedule_a.pdf"
    p.write_bytes(buf.read())
    paths["schedule_a"] = str(p)

    # Schedule B (if interest/dividends)
    if result.sched_b_interest_total > 0 or result.sched_b_dividends_total > 0:
        buf = generate_schedule_b(result)
        p = out / "schedule_b.pdf"
        p.write_bytes(buf.read())
        paths["schedule_b"] = str(p)

    # Schedule D (if capital transactions)
    if result.capital_transactions:
        buf = generate_schedule_d(result)
        p = out / "schedule_d.pdf"
        p.write_bytes(buf.read())
        paths["schedule_d"] = str(p)

    # Schedule 2 + Form 8959 + Form 8960 (if surtaxes apply)
    if result.niit > 0 or result.additional_medicare_tax > 0 or result.se_tax > 0:
        buf = generate_schedule_2(result)
        p = out / "schedule_2.pdf"
        p.write_bytes(buf.read())
        paths["schedule_2"] = str(p)

    if result.additional_medicare_tax > 0:
        buf = generate_form_8959(result)
        p = out / "form_8959.pdf"
        p.write_bytes(buf.read())
        paths["form_8959"] = str(p)

    if result.niit > 0:
        buf = generate_form_8960(result)
        p = out / "form_8960.pdf"
        p.write_bytes(buf.read())
        paths["form_8960"] = str(p)

    # Form 6251 — AMT (if AMT applies)
    if result.amt > 0:
        buf = generate_form_6251(result)
        p = out / "form_6251.pdf"
        p.write_bytes(buf.read())
        paths["form_6251"] = str(p)

    # Form 8863 — Education Credits (if any education credit)
    if result.education_credit > 0 or result.education_credit_refundable > 0:
        buf = generate_form_8863(result)
        p = out / "form_8863.pdf"
        p.write_bytes(buf.read())
        paths["form_8863"] = str(p)

    # Schedule EIC — EITC (if earned income credit)
    if result.eitc > 0:
        buf = generate_schedule_eic(result)
        p = out / "schedule_eic.pdf"
        p.write_bytes(buf.read())
        paths["schedule_eic"] = str(p)

    # Form 2441 — CDCC (if dependent care credit)
    if result.cdcc > 0:
        buf = generate_form_2441(result)
        p = out / "form_2441.pdf"
        p.write_bytes(buf.read())
        paths["form_2441"] = str(p)

    # Form 8880 — Saver's Credit (if retirement savings credit)
    if result.savers_credit > 0:
        buf = generate_form_8880(result)
        p = out / "form_8880.pdf"
        p.write_bytes(buf.read())
        paths["form_8880"] = str(p)

    # Form 8889 — HSA (if HSA contributions)
    if result.hsa_deduction > 0 or result.form_8889_contributions > 0:
        buf = generate_form_8889(result)
        p = out / "form_8889.pdf"
        p.write_bytes(buf.read())
        paths["form_8889"] = str(p)

    # Form 2210 — Estimated Tax Penalty (if penalty assessed)
    if result.estimated_tax_penalty > 0:
        buf = generate_form_2210(result)
        p = out / "form_2210.pdf"
        p.write_bytes(buf.read())
        paths["form_2210"] = str(p)

    # State returns — dispatch by state
    for sr in getattr(result, 'state_returns', []):
        if sr.state_code == "IL":
            # IL has official fillable template
            buf = generate_il1040(result)
            p = out / "il_1040.pdf"
            p.write_bytes(buf.read())
            paths["il_1040"] = str(p)
        elif sr.total_tax > 0 or sr.withholding > 0:
            # Generic ReportLab summary for other states
            buf = generate_generic_state_summary(sr)
            slug = sr.state_code.lower()
            fname = f"state_{slug}_{sr.return_type}.pdf"
            p = out / fname
            p.write_bytes(buf.read())
            paths[f"state_{slug}_{sr.return_type}"] = str(p)

    # Fallback: if no state_returns but IL fields populated (legacy path)
    if not getattr(result, 'state_returns', []) and result.il_line_11_tax > 0:
        buf = generate_il1040(result)
        p = out / "il_1040.pdf"
        p.write_bytes(buf.read())
        paths["il_1040"] = str(p)

    return paths
