apiVersion: v1
kind: Service
metadata:
  name: taxlens-api
  labels:
    app.kubernetes.io/name: taxlens
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: taxlens
    app.kubernetes.io/component: api
