apiVersion: v1
kind: PersistentVolume
metadata:
  name: taxlens-dolt-pv
spec:
  capacity:
    storage: {{ .Values.dolt.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.dolt.pvc.storageClass }}
  local:
    path: /opt/k8s-pers/vol1/taxlens-dolt
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - mgplcb05
  claimRef:
    namespace: taxlens
    name: {{ .Values.dolt.pvc.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dolt.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.dolt.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.dolt.pvc.size }}
